=== Lazhari/NMMS/Person.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" version="1.0"> 
	<xsd:element name="personnes">
			<xsd:complexType>
				<xsd:sequence>	
					<xsd:element name="personne" maxOccurs="unbounded">
						<xsd:complexType>
							<xsd:sequence>
								<xsd:element name="nom" type="xsd:string" minOccurs="1" maxOccurs="1"/>
								<xsd:element name="prenom" type="xsd:string" minOccurs="1" maxOccurs="1"/>		
							</xsd:sequence>
						</xsd:complexType>
					</xsd:element>
				</xsd:sequence>
			</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== Lazhari/NMMS/Person.xml
<?xml version="1.0" encoding="UTF-8"?>
<personnes xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="Person.xsd">	
	<personne >
		<nom>dupon</nom>
		<prenom>pierre</prenom>	
	</personne>
	<personne>
		<nom>durant</nom>
		<prenom>jean</prenom>	
	</personne>
	<personne>
		<nom>martin</nom>
		<prenom>gilles</prenom>	
	</personne>
</personnes>
